package org.firstinspires.ftc.teamcode.autodesigner;

public enum ElectronicType {
    DcMotor,
    GoBILDA5201Series,
    GoBILDA5202Series,
    Matric12vMotor,
    MatrixLegacyMotor,
    NeveRest20Gearmotor,
    NeveRest3_7GearmotorV1,
    NeveRest40Gearmotor,
    NeveRest60Gearmotor,
    RevRobotics20HdHexMotor,
    RevRobotics40HdHexMotor,
    RevRoboticsCoreHexMotor,
    TetrixMotor,
    UnspecifiedMotor,
    AdafruitBNO055IMU,
    NavxMicroNavigationSensor,
    LynxEmbeddedIMU,
    ModernRoboticsAnalogOpticalDistanceSensor,
    ModernRoboticsI2cCompassSensor,
    ModernRoboticsI2cRangeSensor,
    ModernRoboticsTouchSensor,
    Rev2mDistanceSensor,
    RevBlinkinLedDriver,
    RevColorSensorV3,
    RevSPARKMini,
    RevTouchSensor,
    AnalogInput,
    CRServo,
    DigitalChannellmpl,
    LED,
    Servo,
}
